plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.139'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    // Add here additional repositories if required by some of the dependencies below.
    mavenCentral()
    maven {
        url "https://cursemaven.com"
    }

    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}

base {
    archivesName = mod_id
}

// Mojang ships Java 21 to end users in 1.21.1, so mods should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    // Specify the version of NeoForge to use.
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    // This line is optional. Access Transformers are automatically detected
    // accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // gameDirectory = project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        // applies to all the run configs above
        configureEach {
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // multi mod projects should define one per mod
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    //JEI
    // compile against the JEI API but do not include it at runtime
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    // at runtime, use the full JEI jar for NeoForge
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")


    //Moonlight Lib 1.21-2.29.4
    //implementation "curse.maven:selene-499980:7396730"
    //1.21-2.29.11
    //implementation "curse.maven:selene-499980:7473045"
    //1.21-2.29.14
    //implementation "curse.maven:selene-499980:7511744"
    //1.21-2.29.16
    implementation "curse.maven:selene-499980:7522321"

    //Every Compat - Wood Good 1.21-2.11.23
    //implementation "curse.maven:every-compat-628539:7382431"
    //1.21-2.11.24
    //implementation "curse.maven:every-compat-628539:7436223"
    //1.21-2.11.25
    implementation "curse.maven:every-compat-628539:7528817"

    //Stone Zone - 1.21.211.6
    //implementation "curse.maven:stone-zone-1154622:7339708"
    //1.21-2.11.7
    //implementation "curse.maven:stone-zone-1154622:7439162"
    //1.21-2.11.8
    implementation "curse.maven:stone-zone-1154622:7534582"

    //TerraFirmaCraft 1.21.1-4.0.17
    //implementation "curse.maven:terrafirmacraft-302973:7452541"
    //1.21.1-4.0.18-beta
    //implementation "curse.maven:terrafirmacraft-302973:7476548"
    //1.21.1-4.0.19
    implementation "curse.maven:terrafirmacraft-302973:7634816"

    //Patchoili 1.21.1-92
    implementation "curse.maven:patchouli-306770:6842247"

    //Polytone 1.21-3.6.1
    implementation "curse.maven:polytone-958094:7368113"

    //Firmalife 1.21.1-3.0.3
    implementation "curse.maven:firmalife-453394:7498010"

    //Roof and Roads 1.0.0-1.21.1
    implementation "curse.maven:roads-and-roofs-tfc-1048212:7399178"
    //Block Runner
    implementation("curse.maven:block-runner-442842:6215039")
    implementation("curse.maven:puzzles-lib-495476:7140307")

    //ArborFirma afc-2.0.5-1.21.1
    implementation "curse.maven:arborfirmacraft-877545:7314761"

    //Serene Seasons 1.21.1-10.1.0.3
    implementation "curse.maven:serene-seasons-291874:6182596"
    //GlitchCore 1.21.1-2.1.0.0
    implementation "curse.maven:glitchcore-955399:5660740"

    //Legendary Suvival Overhaul 1.21.1-2.4.1
    implementation "curse.maven:legendary-survival-overhaul-840254:7469871"

    //Lithostitched v1.5.7-Neoforge 1.21.1
    implementation "curse.maven:lithostitched-936015:7395055"

    //Beneath
    implementation "curse.maven:beneath-1113980:7503901"

    //cinchsmissingblocks 2.2
    implementation "curse.maven:cinchs-missing-blocks-1338020:7427693"

    //punchy 2.3
    implementation "curse.maven:punchy-1374153:7567680"

    //Hybrid Aquatic 1.5.5
    implementation "curse.maven:hybrid-aquatic-834427:7694018"

    //GeckoLib 4.8.4
    implementation "curse.maven:geckolib-388172:7707149"


    //TODO - testing with Regions Unexplored

    implementation "curse.maven:regions-unexplored-659110:6273893"

    implementation "curse.maven:terrablender-neoforge-940057:6054947"

}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
